### ISSUE TITLE
Error in integration tests after clean install  - Authentication

### ISSUE THREAD

**Issue by etsardou** [rapp-project/rapp-platform-scripts#7]
```
55] cognitive_test_user_scores_arithmetic x1
--> pyOpenSSL does not allow support for tls1_1 and tls1_2. PyOpenSSL needs to be build against openssl-1.0.1 to get  TLSv1.1 and 1.2 support
--> Falling back to TLSv1
Traceback (most recent call last):
  File "/home/rapp/rapp_platform/rapp-platform-catkin-ws/src/rapp-platform/rapp_testing_tools/scripts/rapp_run_test.py", line 25, in <module>
    rapp_testing_tools.main()
  File "/home/rapp/rapp_platform/rapp-platform-catkin-ws/src/rapp-platform/rapp_testing_tools/src/rapp_testing_tools/rapp_testing_core.py", line 300, in main
    execute_tests_all(testFiles, numCalls, threaded)
  File "/home/rapp/rapp_platform/rapp-platform-catkin-ws/src/rapp-platform/rapp_testing_tools/src/rapp_testing_tools/rapp_testing_core.py", line 271, in execute_tests_all
    execute(module, _id)
  File "/home/rapp/rapp_platform/rapp-platform-catkin-ws/src/rapp-platform/rapp_testing_tools/src/rapp_testing_tools/rapp_testing_core.py", line 93, in execute
    tmp = module.RappInterfaceTest()
  File "/home/rapp/rapp_platform/rapp-platform-catkin-ws/src/rapp-platform/rapp_testing_tools/scripts/default_tests/text_to_speech_test_gr_store_file.py", line 33, in __init__
    self.svc = TextToSpeech(language='el', text='Καλησπέρα. Είμαι ο ναο')
  File "/home/rapp/rapp_platform/rapp-platform-catkin-ws/src/rapp-api/python/RappCloud/CloudServices/TextToSpeech.py", line 61, in __init__
    **kwargs
  File "/home/rapp/rapp_platform/rapp-platform-catkin-ws/src/rapp-api/python/RappCloud/CloudServices/Service.py", line 56, in __init__
    self.__controller = ServiceControllerSync(self)
  File "/home/rapp/rapp_platform/rapp-platform-catkin-ws/src/rapp-api/python/RappCloud/ServiceController/ServiceControllerSync.py", line 62, in __init__
    self.__auth = RAPPAuth()
  File "/home/rapp/rapp_platform/rapp-platform-catkin-ws/src/rapp-api/python/RappCloud/ServiceController/RAPPAuth.py", line 52, in __init__
    self.__load_token()
  File "/home/rapp/rapp_platform/rapp-platform-catkin-ws/src/rapp-api/python/RappCloud/ServiceController/RAPPAuth.py", line 72, in __load_token
    self.__read_token_from_file(path.join(self._tokenStoreDir, 'app'))
  File "/home/rapp/rapp_platform/rapp-platform-catkin-ws/src/rapp-api/python/RappCloud/ServiceController/RAPPAuth.py", line 80, in __read_token_from_file
    with open(filepath, 'r') as tokenF:
IOError: [Errno 2] No such file or directory: '/home/rapp/.config/rapp_platform/tokens/app'
```

**Comment by etsardou** [comment]
I re-executed it and worked.. No idea why the first time didn't.
